name : mri

on:
  push:
    branches: ["main"]
    
    jobs:
      build:
        runs-on: ubuntu-latestc #self-hosted
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name:  Set up Python 3.11
            uses: action/setup-python@v3
            with:
              python-version: "3.11"

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install flake8 pytest
              if [ -f req_prod.txt ]; then pip install -r req_prod.txt; fi
                